language: ruby
sudo: false
cache: bundler

rvm:
  - 2.4.2
  - 2.6.0

before_install:
  - gem install bundler
  - gem update bundler

notifications:
  email: false

script:
  - bundle install --jobs=3 --retry=3
  - bundle exec rspec
